import { getPeriodHistory } from './periodHistory';
import { getSymptomLogs } from './symptomLog';
import { getWeightEntries } from './weightStorage';
import { getBloodPressureReadings } from './bloodPressureStorage';
import { getGlucoseReadings } from './glucoseStorage';
import { loadMedications } from './medicationStorage';
import { format } from 'date-fns';

export interface MedicalReportData {
  periods: any[];
  symptoms: any[];
  weight: any[];
  bloodPressure: any[];
  glucose: any[];
  medications: any[];
}

const generateCSVRow = (data: any[]): string => {
  return data
    .map((value) => {
      const stringValue = String(value ?? '');
      // Escape quotes and wrap in quotes if contains comma, quote, or newline
      if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
        return `"${stringValue.replace(/"/g, '""')}"`;
      }
      return stringValue;
    })
    .join(',');
};

export const generatePeriodCSV = (): string => {
  const history = getPeriodHistory();
  const headers = ['Last Period Date', 'Cycle Length (days)', 'Period Duration (days)', 'Timestamp'];
  
  const rows = history.map((entry) => [
    format(new Date(entry.lastPeriodDate), 'yyyy-MM-dd'),
    entry.cycleLength ?? 'N/A',
    entry.periodDuration ?? 'N/A',
    format(new Date(entry.timestamp), 'yyyy-MM-dd HH:mm'),
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateSymptomsCSV = (): string => {
  const symptoms = getSymptomLogs();
  const headers = ['Date', 'Symptoms'];
  
  const rows = symptoms.map((entry) => [
    format(new Date(entry.date), 'yyyy-MM-dd'),
    entry.symptoms?.join('; ') ?? '',
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateWeightCSV = (): string => {
  const weightEntries = getWeightEntries();
  const headers = ['Date', 'Weight (kg)'];
  
  const rows = weightEntries.map((entry) => [
    format(new Date(entry.date), 'yyyy-MM-dd'),
    entry.weight,
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateBloodPressureCSV = (): string => {
  const entries = getBloodPressureReadings();
  const headers = ['Date', 'Time', 'Systolic (mmHg)', 'Diastolic (mmHg)', 'Week'];
  
  const rows = entries.map((entry) => [
    format(new Date(entry.date), 'yyyy-MM-dd'),
    format(new Date(entry.date), 'HH:mm'),
    entry.systolic,
    entry.diastolic,
    entry.week,
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateGlucoseCSV = (): string => {
  const entries = getGlucoseReadings();
  const headers = ['Date', 'Time', 'Glucose Level (mg/dL)', 'Meal Type', 'Week'];
  
  const rows = entries.map((entry) => [
    format(new Date(entry.date), 'yyyy-MM-dd'),
    format(new Date(entry.date), 'HH:mm'),
    entry.glucose,
    entry.mealType,
    entry.week,
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateMedicationCSV = (): string => {
  const entries = loadMedications();
  const headers = ['Medication Name', 'Type', 'Dosage', 'Frequency', 'Start Date'];
  
  const rows = entries.map((entry) => [
    entry.name,
    entry.type,
    entry.dosage,
    entry.frequency,
    format(new Date(entry.startDate), 'yyyy-MM-dd'),
  ]);

  const csvContent = [
    generateCSVRow(headers),
    ...rows.map((row) => generateCSVRow(row)),
  ].join('\n');

  return csvContent;
};

export const generateComprehensiveMedicalReport = (): string => {
  const sections = [
    '# COMPREHENSIVE MEDICAL CYCLE REPORT',
    `Generated on: ${format(new Date(), 'MMMM dd, yyyy')}`,
    '',
    '## MENSTRUAL CYCLE DATA',
    generatePeriodCSV(),
    '',
    '## SYMPTOMS LOG',
    generateSymptomsCSV(),
    '',
    '## WEIGHT TRACKING',
    generateWeightCSV(),
    '',
    '## BLOOD PRESSURE MONITORING',
    generateBloodPressureCSV(),
    '',
    '## GLUCOSE LEVELS',
    generateGlucoseCSV(),
    '',
    '## MEDICATIONS',
    generateMedicationCSV(),
    '',
    '---',
    'Report generated by Period & Pregnancy Tracker App',
    'For medical consultation purposes only',
  ];

  return sections.join('\n');
};

export const downloadCSV = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

export const exportAllMedicalData = () => {
  const timestamp = format(new Date(), 'yyyy-MM-dd');
  
  // Download individual reports
  downloadCSV(`period-data-${timestamp}.csv`, generatePeriodCSV());
  downloadCSV(`symptoms-${timestamp}.csv`, generateSymptomsCSV());
  downloadCSV(`weight-${timestamp}.csv`, generateWeightCSV());
  downloadCSV(`blood-pressure-${timestamp}.csv`, generateBloodPressureCSV());
  downloadCSV(`glucose-${timestamp}.csv`, generateGlucoseCSV());
  downloadCSV(`medications-${timestamp}.csv`, generateMedicationCSV());
  
  // Download comprehensive report
  downloadCSV(`comprehensive-medical-report-${timestamp}.csv`, generateComprehensiveMedicalReport());
};
