import { getSymptomLogs } from "./symptomLog";
import { getAllMoodLogs } from "./moodLog";
import { loadFromLocalStorage } from "./storage";
import { format } from "date-fns";

export const generateSymptomReport = () => {
  const logs = getSymptomLogs();
  const moodLogs = getAllMoodLogs();
  const voiceNotes = loadFromLocalStorage<any[]>("voice-notes") || [];
  const photos = loadFromLocalStorage<any[]>("symptom-photos") || [];

  // Create HTML content
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Symptom Report - ${format(new Date(), "MMMM dd, yyyy")}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          line-height: 1.6;
        }
        h1 {
          color: #EC4899;
          border-bottom: 3px solid #EC4899;
          padding-bottom: 10px;
        }
        h2 {
          color: #8B5CF6;
          margin-top: 30px;
          border-bottom: 2px solid #E9D5FF;
          padding-bottom: 5px;
        }
        .date-entry {
          background: #F9FAFB;
          padding: 15px;
          margin: 15px 0;
          border-radius: 8px;
          border-left: 4px solid #EC4899;
        }
        .date-header {
          font-weight: bold;
          color: #1F2937;
          font-size: 18px;
          margin-bottom: 10px;
        }
        .symptoms {
          display: flex;
          flex-wrap: wrap;
          gap: 8px;
          margin: 10px 0;
        }
        .symptom-tag {
          background: #FDF2F8;
          color: #BE185D;
          padding: 4px 12px;
          border-radius: 16px;
          font-size: 14px;
        }
        .media-info {
          margin-top: 10px;
          padding: 8px;
          background: #FEF3C7;
          border-radius: 4px;
          font-size: 14px;
        }
        .summary {
          background: #DBEAFE;
          padding: 15px;
          border-radius: 8px;
          margin: 20px 0;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #E5E7EB;
          text-align: center;
          color: #6B7280;
          font-size: 12px;
        }
        @media print {
          body { padding: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <h1>Symptom Report</h1>
      <div class="summary">
        <strong>Report Generated:</strong> ${format(new Date(), "MMMM dd, yyyy 'at' h:mm a")}<br>
        <strong>Total Entries:</strong> ${logs.length}<br>
        <strong>Total Photos:</strong> ${photos.length}<br>
        <strong>Total Voice Notes:</strong> ${voiceNotes.length}
      </div>
  `;

  // Group logs by date
  logs.forEach(log => {
    const logDate = new Date(log.date);
    const dateMood = moodLogs.find(m => m.date === log.date);
    const datePhotos = photos.filter(p => p.date === log.date);
    const dateVoiceNotes = voiceNotes.filter(v => v.date === log.date);

    html += `
      <div class="date-entry">
        <div class="date-header">${format(logDate, "EEEE, MMMM dd, yyyy")}</div>
        ${dateMood ? `<div style="margin: 8px 0; font-size: 16px;"><strong>Mood:</strong> ${dateMood.emoji} ${dateMood.mood.charAt(0).toUpperCase() + dateMood.mood.slice(1)}</div>` : ''}
        ${log.symptoms.length > 0 ? `
          <div class="symptoms">
            ${log.symptoms.map(s => `
              <span class="symptom-tag">${formatSymptomName(s)}</span>
            `).join('')}
          </div>
        ` : '<p style="color: #6B7280;">No symptoms recorded</p>'}
        ${datePhotos.length > 0 || dateVoiceNotes.length > 0 ? `
          <div class="media-info">
            ${datePhotos.length > 0 ? `📷 ${datePhotos.length} photo(s) attached` : ''}
            ${datePhotos.length > 0 && dateVoiceNotes.length > 0 ? ' | ' : ''}
            ${dateVoiceNotes.length > 0 ? `🎤 ${dateVoiceNotes.length} voice note(s) recorded` : ''}
          </div>
        ` : ''}
      </div>
    `;
  });

  // Calculate statistics
  const symptomCounts: { [key: string]: number } = {};
  logs.forEach(log => {
    log.symptoms.forEach(symptom => {
      symptomCounts[symptom] = (symptomCounts[symptom] || 0) + 1;
    });
  });

  const sortedSymptoms = Object.entries(symptomCounts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5);

  if (sortedSymptoms.length > 0) {
    html += `
      <h2>Most Common Symptoms</h2>
      <div class="summary">
        ${sortedSymptoms.map(([symptom, count], index) => `
          ${index + 1}. <strong>${formatSymptomName(symptom)}</strong>: ${count} occurrence(s)<br>
        `).join('')}
      </div>
    `;
  }

  html += `
      <div class="footer">
        <p>This report was generated by Flow Fairytale Period Tracker</p>
        <p>For medical advice, please consult with your healthcare provider</p>
      </div>
      <div class="no-print" style="text-align: center; margin: 20px 0;">
        <button onclick="window.print()" style="background: #EC4899; color: white; padding: 12px 24px; border: none; border-radius: 8px; font-size: 16px; cursor: pointer;">
          Print / Save as PDF
        </button>
      </div>
    </body>
    </html>
  `;

  // Open in new window
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
};

const formatSymptomName = (symptom: string) => {
  return symptom
    .split("-")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};